# Generated by Django 2.1.7 on 2020-09-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200904_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(blank=True, default='Team name 353', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teamrank',
            name='teamown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
    ]
