# Generated by Django 2.1.7 on 2020-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200911_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(blank=True, default='Team name 465', max_length=100, null=True),
        ),
    ]
